env:
  browser: true
  es2021: true
  node: true
extends:
  - react-app
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
plugins:
  - react
rules: {}
